/*
  // Initial Setup:
  Create a project in firebase 
  Create Firestore db in test mode.
  Add some demo data
  Add colection employees 
  Add some documents
  Included fields ==> employee_id, name, dept, position.
  note: we also have document id. This will auto generated by firestore

  // NPM Packages: Firebase, React Bootstrap, react-router-dom
  
  // Firebase Config Setup
  2 files ==> firebaseConfig.js firebaseInit.js
   
  Basic components Dashboard, editEmployee, addEmployee, newEmployee etc.

  // Fetching data from firestore.
  


*/
